### ISSUE TITLE
live2调用3G以上内存是正常的吗，貌似还会上涨

### ISSUE THREAD

**Issue by Jasmine-Yli** [WilloIzCitron/ArchiveDustry-Java#10]
如题

**Comment by Jasmine-Yli** [comment]
目前未测试出会使用多少Ram😶‍🌫️😶‍🌫️😶‍🌫️

**Comment by Jasmine-Yli** [comment]
Android客户端146
未加载其它模组

**Comment by WilloIzCitron** [comment]
Garbagecollection fires after the mod ram usage exceed, that's why I recommend allocate ram not under than 2G.

**Comment by WilloIzCitron** [comment]
Fixed in commit 5dd6f73de013fccdc7b38304e20b38b7bae32267
